import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["index.ts"],
  format: ["esm"],
  dts: {
    compilerOptions: {
      incremental: false,
      composite: false,
    },
  },
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  external: [
    "react",
    "react-dom",
    "next",
    "next/image",
    "next/link",
    "next/navigation",
    "@radix-ui/*",
    "lucide-react",
    "@tabler/icons-react",
    "tailwind-merge",
    "clsx",
    "class-variance-authority",
    "recharts",
    "date-fns",
    "react-day-picker",
    "embla-carousel-react",
    "cmdk",
    "input-otp",
    "sonner",
    "vaul",
    "react-resizable-panels",
    "@dnd-kit/*",
    "@origin-space/*",
    "@tanstack/*",
    "three",
    "html-to-image",
    "front-matter",
    "react-shiki",
    "shiki",
    "tw-animate-css",
    "zod",
  ],
});
